name: swim_apps_shared
description: "A new Flutter package project."
version: 0.0.98

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  firebase_auth:
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  provider: ^6.1.2
  cloud_functions: ^6.0.4
  collection: ^1.19.0
  rxdart: ^0.28.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0   # To get the unique Device ID (e.g. androidId)
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^4.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.8
  mocktail: ^1.0.3

flutter:
  assets:
    - assets/fonts/Montserrat/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic